#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#    Nov 26, 2018 07:00:33 PM IST  platform: Windows NT

import sys
import tkinter.messagebox as fmsgbox

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import tictacintro_support
import TICTACTOE_support


def start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1(root)
    tictacintro_support.init(root, top)
    root.mainloop()


def start_game():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root.destroy()
    root = tk.Tk()
    top = Toplevel2(root)
    TICTACTOE_support.init(root, top)
    root.mainloop()


w = None


def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel(root)
    top = Toplevel1(w)
    tictacintro_support.init(w, top, *args, **kwargs)
    return (w, top)


def destroy_Toplevel1():
    global w
    w.destroy()
    w = None


class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#ececec'  # Closest X11 color: 'gray92'
        font12 = "-family {Franklin Gothic Demi Cond} -size 14 -weight"  \
            " normal -slant roman -underline 0 -overstrike 0"
        font15 = "-family {Franklin Gothic Book} -size 13 -weight bold"  \
            " -slant roman -underline 0 -overstrike 0"
        font16 = "-family {Segoe UI Historic} -size 14 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"

        top.geometry("807x540+591+150")
        top.title("New Toplevel")
        top.configure(background="#ffffff")

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.186, rely=0.667, height=43, width=142)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#11b0d8")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font12)
        self.Button1.configure(foreground="#ffffff")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Start Game!''', command=start_game)
        self.Button1.configure(width=142)

        self.menubar = tk.Menu(top, font="TkMenuFont", bg=_bgcolor, fg=_fgcolor)
        top.configure(menu=self.menubar)

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.335, rely=0.259, height=144, width=266)
        self.Label1.configure(background="#ffffff")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self._img1 = tk.PhotoImage(file="Logo.png")
        self.Label1.configure(image=self._img1)
        self.Label1.configure(width=266)

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.397, rely=0.148, height=37, width=168)
        self.Label2.configure(background="#ffffff")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font16)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Welcome to''')
        self.Label2.configure(width=168)

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.657, rely=0.667, height=47, width=96)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#11b0d8")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font=font15)
        self.Button2.configure(foreground="#ffffff")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Quit''', command=root.quit)
        self.Button2.configure(width=96)


bclick = True
x_win = 0
o_win = 0


class Toplevel2:

    def doRefresh(self):
        global bclick
        self.Button1['text'] = ''
        self.Button2['text'] = ''
        self.Button3['text'] = ''
        self.Button4['text'] = ''
        self.Button5['text'] = ''
        self.Button6['text'] = ''
        self.Button7['text'] = ''
        self.Button8['text'] = ''
        self.Button9['text'] = ''
        bclick = True

    def checkTie(self):
        if (self.Button1['text'] != '' and self.Button2['text'] != '' and self.Button3['text'] != '' and
            self.Button4['text'] != '' and self.Button5['text'] != '' and self.Button6['text'] != '' and
                self.Button7['text'] != '' and self.Button8['text'] != '' and self.Button9['text'] != ''):
            fmsgbox.showinfo("", "Its A Tie!")
            self.doRefresh()

    def checkwin(self):
        global x_win, o_win
        if (self.Button1['text'] == 'X' and self.Button2['text'] == 'X' and self.Button3['text'] == 'X' or
            self.Button4['text'] == 'X' and self.Button5['text'] == 'X' and self.Button6['text'] == 'X' or
            self.Button7['text'] == 'X' and self.Button8['text'] == 'X' and self.Button9['text'] == 'X' or
            self.Button3['text'] == 'X' and self.Button5['text'] == 'X' and self.Button7['text'] == 'X' or
            self.Button1['text'] == 'X' and self.Button5['text'] == 'X' and self.Button9['text'] == 'X' or
            self.Button1['text'] == 'X' and self.Button4['text'] == 'X' and self.Button7['text'] == 'X' or
            self.Button2['text'] == 'X' and self.Button5['text'] == 'X' and self.Button8['text'] == 'X' or
                self.Button3['text'] == 'X' and self.Button6['text'] == 'X' and self.Button9['text'] == 'X'):
            if(self.Entry1.get() == ''):
                fmsgbox.showinfo("Player X", "Winner is Player X!!!")
            else:
                fmsgbox.showinfo("Player X", f"Winner is {self.Entry1.get()} !!!")
            x_win += 1
            self.Label6.configure(text=f'''X: {x_win}           O: {o_win}''')
            self.doRefresh()
        elif(self.Button1['text'] == 'O' and self.Button2['text'] == 'O' and self.Button3['text'] == 'O' or
             self.Button4['text'] == 'O' and self.Button5['text'] == 'O' and self.Button6['text'] == 'O' or
             self.Button7['text'] == 'O' and self.Button8['text'] == 'O' and self.Button9['text'] == 'O' or
             self.Button3['text'] == 'O' and self.Button5['text'] == 'O' and self.Button7['text'] == 'O' or
             self.Button1['text'] == 'O' and self.Button5['text'] == 'O' and self.Button9['text'] == 'O' or
             self.Button1['text'] == 'O' and self.Button4['text'] == 'O' and self.Button7['text'] == 'O' or
             self.Button2['text'] == 'O' and self.Button5['text'] == 'O' and self.Button8['text'] == 'O' or
                self.Button3['text'] == 'O' and self.Button6['text'] == 'O' and self.Button9['text'] == 'O'):
            if(self.Entry2.get() == ''):
                fmsgbox.showinfo("Player O", "Winner is Player O!!!")
            else:
                fmsgbox.showinfo("Player O", f"Winner is {self.Entry2.get()} !!!")
            o_win += 1
            self.Label6.configure(text=f'''X: {x_win}           O: {o_win}''')
            self.doRefresh()

    def click1(self):
        global bclick
        if self.Button1['text'] == '' and bclick:
            self.Button1.configure(text='''X''')
            bclick = False
        elif self.Button1['text'] == '' and bclick is False:
            self.Button1.configure(text='''O''')
            bclick = True
        self.checkwin()
        self.checkTie()

    def click2(self):
        global bclick
        if self.Button2['text'] == '' and bclick:
            self.Button2.configure(text='''X''')
            bclick = False
        elif self.Button2['text'] == '' and bclick is False:
            self.Button2.configure(text='''O''')
            bclick = True
        self.checkwin()
        self.checkTie()

    def click3(self):
        global bclick
        if self.Button3['text'] == '' and bclick:
            self.Button3.configure(text='''X''')
            bclick = False
        elif self.Button3['text'] == '' and bclick is False:
            self.Button3.configure(text='''O''')
            bclick = True
        self.checkwin()
        self.checkTie()

    def click4(self):
        global bclick
        if self.Button4['text'] == '' and bclick:
            self.Button4.configure(text='''X''')
            bclick = False
        elif self.Button4['text'] == '' and bclick is False:
            self.Button4.configure(text='''O''')
            bclick = True
        self.checkwin()
        self.checkTie()

    def click5(self):
        global bclick
        if self.Button5['text'] == '' and bclick:
            self.Button5.configure(text='''X''')
            bclick = False
        elif self.Button5['text'] == '' and bclick is False:
            self.Button5.configure(text='''O''')
            bclick = True
        self.checkwin()
        self.checkTie()

    def click6(self):
        global bclick
        if self.Button6['text'] == '' and bclick:
            self.Button6.configure(text='''X''')
            bclick = False
        elif self.Button6['text'] == '' and bclick is False:
            self.Button6.configure(text='''O''')
            bclick = True
        self.checkwin()
        self.checkTie()

    def click7(self):
        global bclick
        if self.Button7['text'] == '' and bclick:
            self.Button7.configure(text='''X''')
            bclick = False
        elif self.Button7['text'] == '' and bclick is False:
            self.Button7.configure(text='''O''')
            bclick = True
        self.checkwin()
        self.checkTie()

    def click8(self):
        global bclick
        if self.Button8['text'] == '' and bclick:
            self.Button8.configure(text='''X''')
            bclick = False
        elif self.Button8['text'] == '' and bclick is False:
            self.Button8.configure(text='''O''')
            bclick = True
        self.checkwin()
        self.checkTie()

    def click9(self):
        global bclick
        if self.Button9['text'] == '' and bclick:
            self.Button9.configure(text='''X''')
            bclick = False
        elif self.Button9['text'] == '' and bclick is False:
            self.Button9.configure(text='''O''')
            bclick = True
        self.checkwin()
        self.checkTie()

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#ececec'  # Closest X11 color: 'gray92'
        font02 = "-family {Franklin Gothic Demi Cond} -size 24 -weight"  \
            " normal -slant roman -underline 0 -overstrike 0"
        font10 = "-family {Lucida Calligraphy} -size 14 -weight normal"  \
            " -slant roman -underline 1 -overstrike 0"
        font11 = "-family Calibri -size 30 -weight bold -slant roman "  \
            "-underline 1 -overstrike 0"
        font12 = "-family Arial -size 12 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"
        font13 = "-family {Lucida Calligraphy} -size 12 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"
        font14 = "-family {Poor Richard} -size 23 -weight normal "  \
            "-slant roman -underline 0 -overstrike 0"
        font15 = "-family {Lucida Calligraphy} -size 15 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"
        font9 = "-family Arial -size 20 -weight bold -slant roman "  \
            "-underline 1 -overstrike 0"

        top.geometry("879x873+100+43")
        top.title("Tic Tac Toe Game")
        top.configure(background="#000000")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.398, rely=0.011, height=61, width=294)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#000000")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font11)
        self.Label1.configure(foreground="#FFFFFF")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''TIC-TAC-TOE''')

        self.Entry1 = tk.Entry(top)
        self.Entry1.place(relx=0.228, rely=0.126, height=20, relwidth=0.164)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(selectforeground="black")

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.034, rely=0.12, height=31, width=144)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#000000")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font12)
        self.Label2.configure(foreground="#ffffff")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Player Name X''')

        self.Canvas1 = tk.Canvas(top)
        self.Canvas1.place(relx=0.068, rely=0.309, relheight=0.412, relwidth=0.41)
        self.Canvas1.configure(background="#9b291c")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(highlightbackground="#d9d9d9")
        self.Canvas1.configure(highlightcolor="black")
        self.Canvas1.configure(insertbackground="black")
        self.Canvas1.configure(relief='ridge')
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(selectforeground="black")
        self.Canvas1.configure(width=360)

        self.Button1 = tk.Button(self.Canvas1)
        self.Button1.place(relx=0.028, rely=0.028, height=105, width=105)
        self.Button1.configure(activebackground="#ff4a98")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#ffffff")
        self.Button1.configure(font=font02)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0", command=self.click1)

        self.Button2 = tk.Button(self.Canvas1)
        self.Button2.place(relx=0.361, rely=0.028, height=105, width=105)
        self.Button2.configure(activebackground="#ff4a98")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#ffffff")
        self.Button2.configure(font=font02)
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0", command=self.click2)

        self.Button3 = tk.Button(self.Canvas1)
        self.Button3.place(relx=0.681, rely=0.028, height=105, width=105)
        self.Button3.configure(activebackground="#ff4a98")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#ffffff")
        self.Button3.configure(font=font02)
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0", command=self.click3)

        self.Button4 = tk.Button(self.Canvas1)
        self.Button4.place(relx=0.028, rely=0.361, height=105, width=105)
        self.Button4.configure(activebackground="#ff4a98")
        self.Button4.configure(activeforeground="#000000")
        self.Button4.configure(background="#ffffff")
        self.Button4.configure(font=font02)
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(foreground="#000000")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="black")
        self.Button4.configure(pady="0", command=self.click4)

        self.Button7 = tk.Button(self.Canvas1)
        self.Button7.place(relx=0.028, rely=0.681, height=105, width=105)
        self.Button7.configure(activebackground="#ff4a98")
        self.Button7.configure(activeforeground="#000000")
        self.Button7.configure(background="#ffffff")
        self.Button7.configure(font=font02)
        self.Button7.configure(disabledforeground="#a3a3a3")
        self.Button7.configure(foreground="#000000")
        self.Button7.configure(highlightbackground="#d9d9d9")
        self.Button7.configure(highlightcolor="black")
        self.Button7.configure(pady="0", command=self.click7)

        self.Button5 = tk.Button(self.Canvas1)
        self.Button5.place(relx=0.361, rely=0.361, height=105, width=105)
        self.Button5.configure(activebackground="#ff4a98")
        self.Button5.configure(activeforeground="#000000")
        self.Button5.configure(background="#ffffff")
        self.Button5.configure(font=font02)
        self.Button5.configure(disabledforeground="#a3a3a3")
        self.Button5.configure(foreground="#000000")
        self.Button5.configure(highlightbackground="#d9d9d9")
        self.Button5.configure(highlightcolor="black")
        self.Button5.configure(pady="0", command=self.click5)

        self.Button8 = tk.Button(self.Canvas1)
        self.Button8.place(relx=0.361, rely=0.681, height=105, width=105)
        self.Button8.configure(activebackground="#ff4a98")
        self.Button8.configure(activeforeground="#000000")
        self.Button8.configure(background="#ffffff")
        self.Button8.configure(font=font02)
        self.Button8.configure(disabledforeground="#a3a3a3")
        self.Button8.configure(foreground="#000000")
        self.Button8.configure(highlightbackground="#d9d9d9")
        self.Button8.configure(highlightcolor="black")
        self.Button8.configure(pady="0", command=self.click8)

        self.Button6 = tk.Button(self.Canvas1)
        self.Button6.place(relx=0.681, rely=0.361, height=105, width=105)
        self.Button6.configure(activebackground="#ff4a98")
        self.Button6.configure(activeforeground="#000000")
        self.Button6.configure(background="#ffffff")
        self.Button6.configure(font=font02)
        self.Button6.configure(disabledforeground="#a3a3a3")
        self.Button6.configure(foreground="#000000")
        self.Button6.configure(highlightbackground="#d9d9d9")
        self.Button6.configure(highlightcolor="black")
        self.Button6.configure(pady="0", command=self.click6)

        self.Button9 = tk.Button(self.Canvas1)
        self.Button9.place(relx=0.681, rely=0.681, height=105, width=105)
        self.Button9.configure(activebackground="#ff4a98")
        self.Button9.configure(activeforeground="#000000")
        self.Button9.configure(background="#ffffff")
        self.Button9.configure(font=font02)
        self.Button9.configure(disabledforeground="#a3a3a3")
        self.Button9.configure(foreground="#000000")
        self.Button9.configure(highlightbackground="#d9d9d9")
        self.Button9.configure(highlightcolor="black")
        self.Button9.configure(pady="0", command=self.click9)

        self.Button10 = tk.Button(top)
        self.Button10.place(relx=0.128, rely=0.8, height=105, width=105)
        self.Button10.configure(activebackground="#ff0000")
        self.Button10.configure(activeforeground="#000000")
        self.Button10.configure(background="#ffffff")
        self.Button10.configure(font=font02)
        self.Button10.configure(disabledforeground="#a3a3a3")
        self.Button10.configure(foreground="#000000")
        self.Button10.configure(highlightbackground="#d9d9d9")
        self.Button10.configure(highlightcolor="black")
        self.Button10.configure(text='''Quit!''')
        self.Button10.configure(pady="0", command=root.destroy)

        self.Label2_17 = tk.Label(self.Canvas1)
        self.Label2_17.place(relx=0.833, rely=-0.111, height=21, width=64)
        self.Label2_17.configure(activebackground="#f9f9f9")
        self.Label2_17.configure(activeforeground="black")
        self.Label2_17.configure(background="#000000")
        self.Label2_17.configure(disabledforeground="#a3a3a3")
        self.Label2_17.configure(font=font12)
        self.Label2_17.configure(foreground="#ffffff")
        self.Label2_17.configure(highlightbackground="#d9d9d9")
        self.Label2_17.configure(highlightcolor="black")
        self.Label2_17.configure(text='''Turn''')

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.762, rely=0.092, height=41, width=134)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#000000")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font=font9)
        self.Label3.configure(foreground="#ffffff")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Result :''')

        self.menubar = tk.Menu(top, font="TkMenuFont", bg=_bgcolor, fg=_fgcolor)
        top.configure(menu=self.menubar)

        self.Message1 = tk.Message(top)
        self.Message1.place(relx=0.614, rely=0.412, relheight=0.049, relwidth=0.262)
        self.Message1.configure(background="#000000")
        self.Message1.configure(font=font10)
        self.Message1.configure(foreground="#ffffff")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(text='''Developed By:''')
        self.Message1.configure(width=230)

        self.Message1_1 = tk.Message(top)
        self.Message1_1.place(relx=0.648, rely=0.298, relheight=0.026, relwidth=0.159)
        self.Message1_1.configure(background="#000000")
        self.Message1_1.configure(font=font10)
        self.Message1_1.configure(foreground="#ffffff")
        self.Message1_1.configure(highlightbackground="#d9d9d9")
        self.Message1_1.configure(highlightcolor="black")
        self.Message1_1.configure(text='''Guided By:''')
        self.Message1_1.configure(width=140)

        self.Message1_3 = tk.Message(top)
        self.Message1_3.place(relx=0.626, rely=0.344, relheight=0.038, relwidth=0.262)
        self.Message1_3.configure(background="#000000")
        self.Message1_3.configure(font=font15)
        self.Message1_3.configure(foreground="#ffffff")
        self.Message1_3.configure(highlightbackground="#d9d9d9")
        self.Message1_3.configure(highlightcolor="#000000")
        self.Message1_3.configure(text='''Nirmala Patil''')
        self.Message1_3.configure(width=230)

        self.Label4 = tk.Label(top)
        self.Label4.place(relx=0.637, rely=0.458, height=41, width=234)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#000000")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font=font13)
        self.Label4.configure(foreground="#ffffff")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''-Akshaykumar Gunari''')

        self.Label4_4 = tk.Label(top)
        self.Label4_4.place(relx=0.637, rely=0.504, height=21, width=104)
        self.Label4_4.configure(activebackground="#f9f9f9")
        self.Label4_4.configure(activeforeground="black")
        self.Label4_4.configure(background="#000000")
        self.Label4_4.configure(disabledforeground="#a3a3a3")
        self.Label4_4.configure(font=font13)
        self.Label4_4.configure(foreground="#ffffff")
        self.Label4_4.configure(highlightbackground="#d9d9d9")
        self.Label4_4.configure(highlightcolor="black")
        self.Label4_4.configure(text='''-Gourav J''')

        self.Label4_5 = tk.Label(top)
        self.Label4_5.place(relx=0.637, rely=0.527, height=41, width=144)
        self.Label4_5.configure(activebackground="#f9f9f9")
        self.Label4_5.configure(activeforeground="black")
        self.Label4_5.configure(background="#000000")
        self.Label4_5.configure(disabledforeground="#a3a3a3")
        self.Label4_5.configure(font=font13)
        self.Label4_5.configure(foreground="#ffffff")
        self.Label4_5.configure(highlightbackground="#d9d9d9")
        self.Label4_5.configure(highlightcolor="black")
        self.Label4_5.configure(text='''-Nitish Bhat''')

        self.Label4_6 = tk.Label(top)
        self.Label4_6.place(relx=0.626, rely=0.573, height=21, width=174)
        self.Label4_6.configure(activebackground="#f9f9f9")
        self.Label4_6.configure(activeforeground="black")
        self.Label4_6.configure(background="#000000")
        self.Label4_6.configure(disabledforeground="#a3a3a3")
        self.Label4_6.configure(font=font13)
        self.Label4_6.configure(foreground="#ffffff")
        self.Label4_6.configure(highlightbackground="#d9d9d9")
        self.Label4_6.configure(highlightcolor="black")
        self.Label4_6.configure(text='''-Akshata Patil''')

        self.Label4_7 = tk.Label(top)
        self.Label4_7.place(relx=0.626, rely=0.596, height=31, width=264)
        self.Label4_7.configure(activebackground="#f9f9f9")
        self.Label4_7.configure(activeforeground="black")
        self.Label4_7.configure(background="#000000")
        self.Label4_7.configure(disabledforeground="#a3a3a3")
        self.Label4_7.configure(font=font13)
        self.Label4_7.configure(foreground="#ffffff")
        self.Label4_7.configure(highlightbackground="#d9d9d9")
        self.Label4_7.configure(highlightcolor="black")
        self.Label4_7.configure(text='''-Anuradha Tasgaonkar''')

        self.Label5 = tk.Label(top)
        self.Label5.place(relx=0.626, rely=0.653, height=275, width=277)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self._img1 = tk.PhotoImage(file="./kletech_logo.png")
        self.Label5.configure(image=self._img1)
        self.Label5.configure(text='''Label''')

        self.Label6 = tk.Label(top)
        self.Label6.place(relx=0.728, rely=0.149, height=51, width=183)
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(background="#000000")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(font=font14)
        self.Label6.configure(foreground="#ffffff")
        self.Label6.configure(highlightbackground="#d9d9d9")
        self.Label6.configure(highlightcolor="black")
        self.Label6.configure(text=f'''X: {x_win}           O: {o_win}''')

        self.Label2_1 = tk.Label(top)
        self.Label2_1.place(relx=0.034, rely=0.172, height=31, width=144)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(background="#000000")
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(font=font12)
        self.Label2_1.configure(foreground="#ffffff")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.Label2_1.configure(text='''Player Name O''')

        self.Entry2 = tk.Entry(top)
        self.Entry2.place(relx=0.228, rely=0.178, height=20, relwidth=0.164)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(highlightbackground="#d9d9d9")
        self.Entry2.configure(highlightcolor="black")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(selectbackground="#c4c4c4")
        self.Entry2.configure(selectforeground="black")


if __name__ == '__main__':
    start_gui()
